M48
; DRILL file {KiCad 7.0.7} date Thu Nov  2 23:48:09 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-02T23:48:09+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X3.2138Y-3.4285
X3.4414Y-3.4285
T2
X0.2783Y-3.4448
X0.5932Y-3.4448
T0
M30
